const object = {
  deckName: "Standard",
  cards: [
    {
      cardName: "Blue-1",
      color: "blue",
      number: "1",
      keyCopy: "1",
    },
    {
      cardName: "Blue-1",
      color: "blue",
      number: "1",
      keyCopy: "2",
    },
    {
      cardName: "Blue-1",
      color: "blue",
      number: "1",
      keyCopy: "3",
    },
    {
      cardName: "Blue-2",
      color: "blue",
      number: "2",
      keyCopy: "1",
    },
    {
      cardName: "Blue-2",
      color: "blue",
      number: "2",
      keyCopy: "2",
    },
    {
      cardName: "Blue-3",
      color: "blue",
      number: "3",
      keyCopy: "1",
    },
    {
      cardName: "Blue-3",
      color: "blue",
      number: "3",
      keyCopy: "2",
    },
    {
      cardName: "Blue-4",
      color: "blue",
      number: "4",
      keyCopy: "1",
    },
    {
      cardName: "Blue-4",
      color: "blue",
      number: "4",
      keyCopy: "2",
    },
    {
      cardName: "Blue-5",
      color: "blue",
      number: "5",
    },
    {
      cardName: "Red-1",
      color: "red",
      number: "1",
      keyCopy: "1",
    },
    {
      cardName: "Red-1",
      color: "red",
      number: "1",
      keyCopy: "2",
    },
    {
      cardName: "Red-1",
      color: "red",
      number: "1",
      keyCopy: "3",
    },
    {
      cardName: "Red-2",
      color: "red",
      number: "2",
      keyCopy: "1",
    },
    {
      cardName: "Red-2",
      color: "red",
      number: "2",
      keyCopy: "2",
    },
    {
      cardName: "Red-3",
      color: "red",
      number: "3",
      keyCopy: "1",
    },
    {
      cardName: "Red-3",
      color: "red",
      number: "3",
      keyCopy: "2",
    },
    {
      cardName: "Red-4",
      color: "red",
      number: "4",
      keyCopy: "1",
    },
    {
      cardName: "Red-4",
      color: "red",
      number: "4",
      keyCopy: "2",
    },
    {
      cardName: "Red-5",
      color: "red",
      number: "5",
      keyCopy: "1",
    },
    {
      cardName: "White-1",
      color: "white",
      number: "1",
      keyCopy: "1",
    },
    {
      cardName: "White-1",
      color: "white",
      number: "1",
      keyCopy: "2",
    },
    {
      cardName: "White-1",
      color: "white",
      number: "1",
      keyCopy: "3",
    },
    {
      cardName: "White-2",
      color: "white",
      number: "2",
      keyCopy: "1",
    },
    {
      cardName: "White-2",
      color: "white",
      number: "2",
      keyCopy: "2",
    },
    {
      cardName: "White-3",
      color: "white",
      number: "3",
      keyCopy: "1",
    },
    {
      cardName: "White-3",
      color: "white",
      number: "3",
      keyCopy: "2",
    },
    {
      cardName: "White-4",
      color: "white",
      number: "4",
      keyCopy: "1",
    },
    {
      cardName: "White-4",
      color: "white",
      number: "4",
      keyCopy: "2",
    },
    {
      cardName: "White-5",
      color: "white",
      number: "5",
      keyCopy: "1",
    },
    {
      cardName: "Green-1",
      color: "green",
      number: "1",
      keyCopy: "1",
    },
    {
      cardName: "Green-1",
      color: "green",
      number: "1",
      keyCopy: "2",
    },
    {
      cardName: "Green-1",
      color: "green",
      number: "1",
      keyCopy: "3",
    },
    {
      cardName: "Green-2",
      color: "green",
      number: "2",
      keyCopy: "1",
    },
    {
      cardName: "Green-2",
      color: "green",
      number: "2",
      keyCopy: "2",
    },
    {
      cardName: "Green-3",
      color: "green",
      number: "3",
      keyCopy: "1",
    },
    {
      cardName: "Green-3",
      color: "green",
      number: "3",
      keyCopy: "2",
    },
    {
      cardName: "Green-4",
      color: "green",
      number: "4",
      keyCopy: "1",
    },
    {
      cardName: "Green-4",
      color: "green",
      number: "4",
      keyCopy: "2",
    },
    {
      cardName: "Green-5",
      color: "green",
      number: "5",
      keyCopy: "1",
    },
    {
      cardName: "Yellow-1",
      color: "yellow",
      number: "1",
      keyCopy: "1",
    },
    {
      cardName: "Yellow-1",
      color: "yellow",
      number: "1",
      keyCopy: "2",
    },
    {
      cardName: "Yellow-1",
      color: "yellow",
      number: "1",
      keyCopy: "3",
    },
    {
      cardName: "Yellow-2",
      color: "yellow",
      number: "2",
      keyCopy: "1",
    },
    {
      cardName: "Yellow-2",
      color: "yellow",
      number: "2",
      keyCopy: "2",
    },
    {
      cardName: "Yellow-3",
      color: "yellow",
      number: "3",
      keyCopy: "1",
    },
    {
      cardName: "Yellow-3",
      color: "yellow",
      number: "3",
      keyCopy: "2",
    },
    {
      cardName: "Yellow-4",
      color: "yellow",
      number: "4",
      keyCopy: "1",
    },
    {
      cardName: "Yellow-4",
      color: "yellow",
      number: "4",
      keyCopy: "2",
    },
    {
      cardName: "Yellow-5",
      color: "yellow",
      number: "5",
      keyCopy: "1",
    },
  ],
};
